- name: Disable AppArmor
  service:
    name: apparmor
    state: stopped
    enabled: no
  register: apparmor_mode
  when: ansible_apparmor.status == "enabled"

- name: Reboot machine following AppArmor state change
  reboot:
    pre_reboot_delay: 5
    post_reboot_delay: 15
    msg: "Reboot initiated by Ansible::Core"
  when: apparmor_mode is changed

# - name: Reboot immediately if there was a change.
#   shell: "sleep 5 && reboot"
#   async: 1
#   poll: 0
#   when: apparmor_mode is changed

- name: Core.AppArmor - Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 10
    delay: 5
    timeout: 300
  when: apparmor_mode is changed