---
# tasks file for core::ssh

  - name: SSH Service - Install/Update package
    package:
      name: openssh-server

  - name: SSH Service - Create configuration from template
    template:
      src: etc/ssh/sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: 0600
    notify: SSHD Restart