# tasks file for core::rhel/selinux

- name: Disable SELinux
  selinux:
    state: disabled
  register: selinux_mode

- name: Reboot machine following SELinux state change
  reboot:
    pre_reboot_delay: 5
    post_reboot_delay: 15
    msg: "Reboot initiated by Ansible::Core"
  when: selinux_mode is changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 10
    delay: 5
    timeout: 300
  when: selinux_mode is changed